version: "3.8"
volumes:
  metadatabase:
  library:
    driver_opts:
      type: ${LIBRARY_VOLUME_TYPE}
      o: ${LIBRARY_VOLUME_OPTIONS}
      device: ${LIBRARY_VOLUME_DEVICE}
services:
  liquidsoap:
    image: icedream/liquidsoap
    build: liquidsoap/
    # HACK - haven't quite figured out the ports SRT/NDI use
    network_mode: host
    # ports:
    #   - "8050:8050"
    #   - "8051:8051"
    #   - "9000:9000"
    #   - "9000:9000/udp"
    stop_signal: SIGTERM
    restart: always
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 768M
  ndi-to-srt:
    image: icedream/ndi-to-srt
    restart: always
    build: ndi-to-srt
    # HACK - haven't quite figured out the ports SRT/NDI use
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 64M
  tunaposter:
    image: icedream/tunaposter
    restart: always
    build:
      context: .
      dockerfile: tunaposter.Dockerfile
    # HACK - haven't quite figured out the ports SRT/NDI use
    network_mode: host
    command:
      - /usr/local/bin/tunaposter
      # tuna source URL
      - ${TUNA_SOURCE_URL}
      # liquidsoap metadata API URL
      - http://127.0.0.1:21338
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 32M
  metacollector:
    image: icedream/metacollector
    restart: always
    build: metacollector/
    ports:
      - "8080:8080"
    environment:
      METACOLLECTOR_DATABASE_URL: /database/app.db
      METACOLLECTOR_LIBRARY_PATHS: /library
      METACOLLECTOR_SERVER_ADDRESS: ":8080"
    volumes:
      - library:/library
      - metadatabase:/database
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 128M
