version: "3.8"
volumes:
  metadatabase:
  library:
    driver_opts:
      type: "${LIBRARY_VOLUME_TYPE:-local}"
      o: "${LIBRARY_VOLUME_OPTIONS:-defaults}"
      device: "${LIBRARY_VOLUME_DEVICE:-/var/tmp/whatever}"
services:
  liquidsoap:
    image: icedream/liquidsoap
    build: liquidsoap/
    # HACK - haven't quite figured out the ports SRT/NDI use
    network_mode: host
    # ports:
    #   - "8050:8050"
    #   - "8051:8051"
    #   - "9000:9000"
    #   - "9000:9000/udp"
    stop_signal: SIGTERM
    restart: always
    devices:
      - /dev/dri:/dev/dri
    environment:
      - INTERNAL_ICECAST_USERNAME=${INTERNAL_ICECAST_USERNAME:-source}
      - INTERNAL_ICECAST_PASSWORD=${INTERNAL_ICECAST_PASSWORD:-source}
      - REKTNETWORK_USERNAME
      - REKTNETWORK_PASSWORD
      - STREAM_NAME
      - STREAM_DESCRIPTION
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 768M
  ndi-feeder:
    image: icedream/ndi-feeder
    restart: always
    build: ndi-feeder
    # HACK - haven't quite figured out the ports SRT/NDI use
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 64M
  metacollector:
    image: icedream/metacollector
    restart: always
    build: metacollector/
    ports:
      - "8080:8080"
    environment:
      METACOLLECTOR_DATABASE_URL: /database/app.db
      METACOLLECTOR_LIBRARY_PATHS: /library
      METACOLLECTOR_SERVER_ADDRESS: ":8080"
    volumes:
      - library:/library
      - metadatabase:/database
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 128M
  icecast:
    image: icedream/icecast
    build: images/icecast-2.4.4
    restart: always
    volumes:
      - "/share/VM_Disks/Docker/IcedreamLive/config/icecast/icecast.xml:/icecast.xml:ro"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 128M
