stream_name=environment.get(default="Spontaneously live in the mix", "STREAM_NAME")
stream_description=environment.get(default="", "STREAM_DESCRIPTION")

internal_icecast_username=environment.get(default="source", "INTERNAL_ICECAST_USERNAME")
internal_icecast_password=environment.get(default="source", "INTERNAL_ICECAST_PASSWORD")

rektfm_username=environment.get("REKTNETWORK_USERNAME")
rektfm_password=environment.get("REKTNETWORK_PASSWORD")
